version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

#  nestjs-app:
#    build: .
#    restart: always
#    ports:
#      - 3000:3000
#    volumes:
#      - .:/usr/src/app
#    environment:
#      SERVER_ADDRESS: 0.0.0.0:3000
#      SERVER_HOST: localhost:3000/
#      CONTEXT_TIMEOUT: 60
#      DB_HOST: mongo
#      DB_PORT: 27017
#      DB_USER: root
#      DB_PASS: example
#      DB_NAME: cluster0
#      ACCESS_TOKEN_EXPIRY_HOUR: 555
#      REFRESH_TOKEN_EXPIRY_HOUR: 72
#      ACCESS_TOKEN_SECRET: supersecretkeyforaccesstoken
#      REFRESH_TOKEN_SECRET: supersecretkeyforrefreshtoken
#      SMTPServer: outlook.office365.com
#      SMTPPort: 587
#      SMTPUser: your-smtp-username
#      SMTPPassword: your-smtp-password
